baseURL = 'https://masterdubs.com/'
languageCode = 'en-us'
title = 'Dubs blog'
theme = "hugo-theme-monochrome"
googleAnalytics = "G-2974LT1M3Z"
enableEmoji = true

[params]
  footer = "Copyright © 2021 by Dubs"
  enableCollapsibleTOC = true
  enableSiteSearch = true
  GitHubUser = "masterdubs"
  AuthorName = "Dubs"
  googleAnalytics = "G-2974LT1M3Z"


[build]
  writeStats = true